#!/usr/bin/python

import os
import sys

if __name__ == "__main__":
    sys.path.insert(0, "/srv/minv")
    os.environ["DJANGO_SETTINGS_MODULE"] = "minv_instance.settings"

    from django.core.management import execute_from_command_line

    execute_from_command_line(sys.argv)
